port: 8080
api_port: 9091
webhook_url: "" # Slack/Discord Webhook URL
ssl_domain: ""  # Set domain to enable Auto SSL (e.g., "example.com")

backends:
  - "backend1:80"
  - "backend2:80"

rules:
  "/admin": "backend1:80"
  "/img":   "backend2:80"
  "/payment": "backend1:80"